# Generated by Django 5.0.4 on 2024-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_tasks_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="other",
            field=models.BooleanField(default=False),
        ),
    ]
